# Generated by Django 3.0.5 on 2020-04-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apt',
            old_name='s_major',
            new_name='apt_name',
        ),
        migrations.RemoveField(
            model_name='apt',
            name='s_age',
        ),
        migrations.RemoveField(
            model_name='apt',
            name='s_gender',
        ),
        migrations.RemoveField(
            model_name='apt',
            name='s_grade',
        ),
        migrations.RemoveField(
            model_name='apt',
            name='s_name',
        ),
    ]
