# Generated by Django 3.0.5 on 2020-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptmanager', '0003_auto_20200513_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apt_name',
            new_name='apt',
        ),
    ]
